version: '3'
services:
  steer_drive:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ..:/workspaces/steer_drive:cached
      # device access
      - /dev:/dev
    working_dir: /workspaces/steer_drive
    tty: true
    command: sleep inf
    # device access
    privileged: true
